"""
Export Service for MffConvert study materials.
Produces Markdown, Printable HTML/PDF, Flashcards CSV (Anki), and JSON archives.
"""

import json
from typing import Dict, Any, List

class ExportService:
    @staticmethod
    def to_markdown(project: Dict[str, Any], study_materials: Dict[str, Any]) -> str:
        title = project.get("title", "Lecture Study Guide")
        duration = project.get("duration", 0.0)
        min_d = int(duration // 60)
        sec_d = int(duration % 60)

        md = f"# {title}\n\n"
        md += f"- **Duration**: {min_d}m {sec_d}s\n"
        md += f"- **Generated By**: MffConvert (Free & Local-First AI Study Tool)\n"
        md += f"- **Privacy**: 100% Processed Locally\n\n"
        md += "---\n\n"

        md += study_materials.get("deep_notes", "") + "\n\n"

        # Chapters
        chapters = study_materials.get("chapters", [])
        if chapters:
            md += "## Lecture Milestones & Chapters\n\n"
            for ch in chapters:
                ts = ch.get("start_time", 0.0)
                md += f"### {ch.get('title')} `[{int(ts//60):02d}:{int(ts%60):02d}]`\n"
                md += f"{ch.get('summary')}\n\n"

        # Formulas
        formulas = study_materials.get("formulas", [])
        if formulas:
            md += "## Formulas & Equations\n\n"
            for f in formulas:
                ts = f.get("timestamp", 0.0)
                md += f"- **{f.get('name')}** `[{int(ts//60):02d}:{int(ts%60):02d}]`\n"
                md += f"  $$\n  {f.get('latex')}\n  $$\n"
                md += f"  *{f.get('explanation')}*\n\n"

        # Questions
        questions = study_materials.get("questions", [])
        if questions:
            md += "## Solved Problems\n\n"
            for q in questions:
                ts = q.get("timestamp", 0.0)
                md += f"#### Q: {q.get('question')} `[{int(ts//60):02d}:{int(ts%60):02d}]`\n"
                md += f"**Solution:** {q.get('solution')}\n\n"

        return md

    @staticmethod
    def to_anki_csv(study_materials: Dict[str, Any]) -> str:
        """Exports flashcards formatted for Anki / Quizlet CSV import."""
        flashcards = study_materials.get("flashcards", [])
        lines = ["#separator:Tab", "#html:true", "#tags column:3"]
        for fc in flashcards:
            front = fc.get("front", "").replace("\t", " ").replace("\n", "<br>")
            back = fc.get("back", "").replace("\t", " ").replace("\n", "<br>")
            tag = fc.get("tag", "MffConvert")
            lines.append(f"{front}\t{back}\t{tag}")
        return "\n".join(lines)

    @staticmethod
    def to_printable_html(project: Dict[str, Any], study_materials: Dict[str, Any]) -> str:
        """Generates self-contained, clean HTML printable with KaTeX support."""
        title = project.get("title", "Lecture Study Guide")
        deep_notes = study_materials.get("deep_notes", "").replace("\n", "<br>")

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{title} — Study Guide</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css">
  <style>
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      line-height: 1.6;
      color: #1a202c;
      max-width: 850px;
      margin: 40px auto;
      padding: 0 20px;
    }}
    h1 {{ border-bottom: 2px solid #3182ce; padding-bottom: 8px; color: #2b6cb0; }}
    h2 {{ color: #2c5282; margin-top: 24px; border-bottom: 1px solid #e2e8f0; }}
    h3 {{ color: #4a5568; }}
    .badge {{
      display: inline-block;
      background: #ebf8ff;
      color: #2b6cb0;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 0.85em;
      margin-bottom: 16px;
    }}
    .box {{
      background: #f7fafc;
      border-left: 4px solid #3182ce;
      padding: 12px 16px;
      margin: 16px 0;
      border-radius: 0 4px 4px 0;
    }}
    @media print {{
      body {{ margin: 10mm; }}
      .no-print {{ display: none; }}
    }}
  </style>
</head>
<body>
  <div class="no-print" style="margin-bottom: 20px;">
    <button onclick="window.print()" style="padding: 8px 16px; background: #3182ce; color: #fff; border: none; border-radius: 4px; cursor: pointer;">Print / Save as PDF</button>
  </div>
  <h1>{title}</h1>
  <div class="badge">100% Free & Local Study Guide by MffConvert</div>
  <div>{deep_notes}</div>
</body>
</html>
"""
        return html
